# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodBookRead' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'SnapKit'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'NSObject+Rx'
    pod 'Then'
    pod 'YYWebImage' # 图片
    pod 'MJRefresh' # 下拉刷新
    pod 'Reusable'
    pod 'Moya'
    pod 'Moya/RxSwift' # 请求
    pod 'HandyJSON', '~> 5.0.0-beta.1' # 数据解析
    pod 'YYAsyncLayer'
    pod 'EmptyDataSet-Swift' # 空数据视图
    pod 'NVActivityIndicatorView' # 加载样式
    pod 'TransitionButton' # 动画按钮
    pod 'IQKeyboardManagerSwift' # 键盘
    pod 'YYText' # 键盘
    pod 'Toast-Swift'
    pod 'RealmSwift'
    # Pods for GoodBookRead
    
end
