# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodBookRead' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'SnapKit'
 pod 'SwiftyJSON'
 pod 'RxSwift'
 pod 'RxCocoa'
 pod 'RxDataSources'
 pod 'NSObject+Rx'
 pod 'Then'
 pod 'YYWebImage'
 pod 'MJRefresh'
 pod 'Reusable'
 pod 'Moya'
 pod 'HandyJSON'
 pod 'MBProgressHUD'
 pod 'YYAsyncLayer'
 pod 'EmptyDataSet-Swift'

  # Pods for GoodBookRead

end
